version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19

  pre_build:
    commands:
      - docker login -u squeakyai -p "${SQUEAKY_DOCKER_PASSWORD}"
      - $(aws ecr get-login --no-include-email)

  build:
    commands:
      # Build and push the docker image
      - docker build --platform linux/arm64 -t web:latest .
      - docker tag web:latest "${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/web:latest"
      - docker push "${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/web:latest"
      # Extract the .next directory and publish it to S3
      - CID=$(docker create web)
      - docker cp ${CID}:/app/.next/static /tmp/
      - docker rm ${CID}
      - aws s3 sync /tmp/static s3://cdn.squeaky.ai/web/_next/static --delete

  post_build:
    commands:
      - aws ecs update-service --cluster squeaky --service web --force-new-deployment
      - aws ecs wait services-stable --cluster squeaky --services web

cache:
  paths:
    - node_modules/**/*