version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  build:
    commands:
      - yarn install
      - yarn next build
      - yarn next export

  post_build:
    commands:
      - aws s3 sync ./out s3://squeaky.ai/ --delete
      - aws cloudfront create-invalidation --distribution-id E33C9U0CJ86R7L --paths /*

cache:
  paths:
    - node_modules/**/*
